name: Build C Extension Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    #ubuntu-latest, macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.14' 

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0  # Upgrade this version tag
        env:
          CIBW_BUILD: "cp314-*"
          CIBW_ENABLE: "cpython-prerelease"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
